module.exports = {
  preset: 'jest-expo',
  setupFilesAfterEnv: ['<rootDir>/__tests__/test-utils/jest.setup.ts'],
  testMatch: [
    '<rootDir>/__tests__/**/*.test.ts',
    '<rootDir>/__tests__/**/*.test.tsx',
    '<rootDir>/src/**/*.test.ts',
    '<rootDir>/src/**/*.test.tsx',
  ],
  testPathIgnorePatterns: ['/node_modules/', '<rootDir>/__tests__/test-utils/'],
  collectCoverageFrom: [
    'src/domain/**/*.{ts,tsx}',
    'src/application/**/*.{ts,tsx}',
    'src/infra/**/*.{ts,tsx}',
    'src/presentation/**/*.{ts,tsx}',
    '!src/**/index.ts',
    '!src/**/*.d.ts',
    '!src/infra/reactotron/**',
    '!src/infra/di/container.ts',
    '!src/infra/http/httpClient.ts',
    '!src/infra/repositories/InMemory*.ts',
    '!src/infra/repositories/fixtures/**',
    '!src/infra/theme/AppThemeProvider.tsx',
    '!src/infra/theme/themeStorage.ts',
    '!src/infra/theme/fonts.ts',
    '!src/infra/theme/lightTheme.ts',
    '!src/infra/theme/darkTheme.ts',
    '!src/infra/theme/tokens/**',
    '!src/infra/theme/languageColors.ts',
    '!src/infra/query/**',
    '!src/infra/repositories/GitHub*Repository.ts',
    '!src/presentation/navigation/**',
    '!src/presentation/design-system/**',
  ],
  coverageThreshold: {
    global: {
      statements: 80,
      branches: 75,
      functions: 80,
      lines: 80,
    },
    './src/domain/': {
      statements: 100,
      branches: 100,
      functions: 100,
      lines: 100,
    },
    './src/application/': {
      statements: 100,
      branches: 95,
      functions: 100,
      lines: 100,
    },
  },
  moduleNameMapper: {
    '^@/domain/(.*)$': '<rootDir>/src/domain/$1',
    '^@/application/(.*)$': '<rootDir>/src/application/$1',
    '^@/infrastructure/(.*)$': '<rootDir>/src/infrastructure/$1',
    '^@/presentation/(.*)$': '<rootDir>/src/presentation/$1',
  },
};
